// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwINGAtn3AlPG3cN4cCF2-81Fjfic3YC8',
    appId: '1:684091793203:android:1104a68fc7175d8a5fa846',
    messagingSenderId: '684091793203',
    projectId: 'san3a-ee8fe',
    storageBucket: 'san3a-ee8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHg_aNTKxjsTb0G2lvMpOEwPdty-V7mw',
    appId: '1:684091793203:ios:2bcce36e825a966e5fa846',
    messagingSenderId: '684091793203',
    projectId: 'san3a-ee8fe',
    storageBucket: 'san3a-ee8fe.firebasestorage.app',
    androidClientId: '684091793203-m6sk7toorpntq2iivr13fbgr81jo8jhp.apps.googleusercontent.com',
    iosClientId: '684091793203-rj0jjp2rv9a2ukqhpvq1t97s45n15ji5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpFrontend',
  );

}